# Flow Full-stack Signals
#com.vaadin.experimental.flowFullstackSignals=true
# Tailwind CSS framework
# com.vaadin.experimental.tailwindCss=true
# AI components (AIOrchestrator)
com.vaadin.experimental.aiComponents=true
# Modular Upload (UploadManager, UploadButton, etc.)
com.vaadin.experimental.modularUpload=true
# Message List attachments
com.vaadin.experimental.messageListAttachments=true

com.vaadin.experimental.sliderComponent=true
com.vaadin.experimental.badgeComponent=true
